import numpy as np
import yaml
from pathlib import Path
from scripts.extractor import extract_frames
from scripts.aruco_detector import detect_markers
from scripts.colmap_wrapper import run_colmap_reconstruction
from scripts.model_scaler import calculate_scale
from scripts.calibration_generator import compute_calibration
from scripts.calibration_utils import load_camera_params, validate_calibration_integrity

def main():
    print("--- MVP 3D Reconstruction Pipeline ---")
    
    # Configuration
    VIDEO_INPUT = "data/raw/test_scene.mp4"
    CALIB_IMG_DIR = "data/calibration"  # Directory for checkerboard images
    FRAME_OUTPUT = "frames"
    DATA_OUTPUT = "output/aruco_data.json"
    COLMAP_OUTPUT = "output/colmap"
    CALIB_PATH = "camera_calib.yaml"
    
    # Files generated by COLMAP
    IMAGES_BIN = "output/colmap/sparse/0/images.bin"
    POINTS_BIN = "output/colmap/sparse/0/points3D.bin"
    FINAL_PLY = "output/scaled_model.ply"

    # Step 1: Calibration Computation (US-06)
    # If the file doesn't exist but images do, compute it.
    if not Path(CALIB_PATH).exists():
        if Path(CALIB_IMG_DIR).exists() and list(Path(CALIB_IMG_DIR).glob('*.jpg')):
            print("[Step 1] Computing camera calibration from images...")
            error = compute_calibration(CALIB_IMG_DIR)
            print(f"✅ Calibration generated. Reprojection error: {error:.4f}")
        else:
            print(f"⚠️ {CALIB_PATH} not found and no calibration images available.")
            return

    # Step 2: Load and Validate (US-14)
    print("[Step 2] Loading camera parameters...")
    K, D = load_camera_params(CALIB_PATH)
    if not validate_calibration_integrity(K, D):
        print("❌ Critical Error: Calibration data is invalid.")
        return

    # Step 3: Extraction (US-05 / US-13)
    print("[Step 3] Extracting frames from video...")
    extract_frames(VIDEO_INPUT, FRAME_OUTPUT, fps=2)

    # Step 4: Detection (US-07 / US-15)
    print("[Step 4] Detecting ArUco markers...")
    # Detection results are used to define the spatial reference frame [cite: 1, 2]
    num_detected = detect_markers(FRAME_OUTPUT, DATA_OUTPUT)
    print(f"✅ Markers detected in {num_detected} frames.")

    # Step 5: COLMAP Reconstruction (US-08 / US-17)
    print("[Step 5] Starting COLMAP Structure from Motion...")
    # This generates a sparse model and camera trajectory [cite: 1, 8]
    success = run_colmap_reconstruction(FRAME_OUTPUT, COLMAP_OUTPUT)
    
    if not success:
        print("❌ Reconstruction failed.")
        return

    # Step 6: Scaling and Export (US-09 / US-19)
    if Path(IMAGES_BIN).exists():
        print("[Step 6] Aligning scale with ArUco measurements...")
        # Transforms COLMAP units into real-world meters 
        scale = calculate_scale(DATA_OUTPUT, IMAGES_BIN)
        print(f"✅ Final Scale Factor: {scale:.4f}")
        
        if Path(POINTS_BIN).exists():
            from scripts.ply_exporter import export_scaled_ply
            export_scaled_ply(POINTS_BIN, FINAL_PLY, scale)
            print(f"--- SUCCESS: 3D scene saved to {FINAL_PLY} ---")
    else:
        print("❌ Scaling failed: COLMAP output files missing.")

if __name__ == "__main__":
    main()